### ISSUE TITLE
Is it possible to use it with the simulator?

### ISSUE THREAD

**Issue by jsdario** [jacobrosenthal/react-native-ble#13]
Hi, sorry for the beginner question, but I am struggling to find examples.
Do you use any simulator to develop with react-native? I am getting "unsupported" state while using iOS simulator within OSX.

Hope it is my bad!

**Comment by rclai** [comment]
No Apple, doesn't let you unfortunately. Not even with Bluetooth dongles.

**Comment by jsdario** [comment]
Thanks for the reply. Any advice or tip on how you debug it on Android and iOS?
Do you run it directly on a device?

**Comment by rclai** [comment]
Yes, you must run it on a device.

**Comment by jacobrosenthal** [comment]
One tip is to write your app logic on your laptop with noble, and when you're happy with it finally test it on the phone which is obviously a much more arduous process.
