### ISSUE TITLE
"Data must be a buffer" error from noble.js

### ISSUE THREAD

**Issue by eriihine** [jacobrosenthal/react-native-ble#16]
Run in to a error "data must be a buffer" after merging the latest changes from master branch to my project. The error happens when writing to a characteristic in iOS e.g.

someCharacteristic.write(new Buffer.from(data, "hex");
--> causes an error "data must be a buffer"

This is the same problem as described here:
https://github.com/sandeepmistry/noble/issues/388#issuecomment-214550333

And as described in the above this was worked around by adding a characteristic prototype function in index.js

The prototypes were however removed as part of the recent (July) commit and the problem appeared again.

After adding the characteristic prototype back I got the project working again.

Is the characteristic prototype still needed or should this be handled differently from now on?

**Comment by jacobrosenthal** [comment]
With the 2 new examples Im not seeing this atm. Long termI think this is related to #2
