### ISSUE TITLE
Notify not working on Android

### ISSUE THREAD

**Issue by MasterOfBacon** [jacobrosenthal/react-native-ble#22]
Hello, the notify function doesn't seem to be included as a binding in bindings.android.js. Any reason for this? This API works fine with me in discovering services, characteristics and reading them, but trying to use the notify function gives me an error "undefined is not a function (evaluating 'this._bindings.notify(peripheralUuid,serviceUuid,characteristicUuid,notify)')". Using console.log(noble) right after importing noble gives me the following:

> { state: 'unknown',
I/ReactNativeJS( 7470):   address: 'unknown',
I/ReactNativeJS( 7470):   _bindings: 
I/ReactNativeJS( 7470):    { init: [Function],
I/ReactNativeJS( 7470):      connect: [Function],
I/ReactNativeJS( 7470):      disconnect: [Function],
I/ReactNativeJS( 7470):      startScanning: [Function],
I/ReactNativeJS( 7470):      stopScanning: [Function],
I/ReactNativeJS( 7470):      discoverServices: [Function],
I/ReactNativeJS( 7470):      discoverIncludedServices: [Function],
I/ReactNativeJS( 7470):      discoverCharacteristics: [Function],
I/ReactNativeJS( 7470):      discoverDescriptors: [Function],
I/ReactNativeJS( 7470):      read: [Function],
I/ReactNativeJS( 7470):      write: [Function],
I/ReactNativeJS( 7470):      _events: 
I/ReactNativeJS( 7470):       { stateChange: [Function],
I/ReactNativeJS( 7470):         addressChange: [Function],
I/ReactNativeJS( 7470):         scanStart: [Function],
I/ReactNativeJS( 7470):         scanStop: [Function],
I/ReactNativeJS( 7470):         discover: [Function],
I/ReactNativeJS( 7470):         connect: [Function],
I/ReactNativeJS( 7470):         disconnect: [Function],
I/ReactNativeJS( 7470):         rssiUpdate: [Function],
I/ReactNativeJS( 7470):         servicesDiscover: [Function],
I/ReactNativeJS( 7470):         includedServicesDiscover: [Function],
I/ReactNativeJS( 7470):         characteristicsDiscover: [Function],
I/ReactNativeJS( 7470):         read: [Function],
I/ReactNativeJS( 7470):         write: [Function],
I/ReactNativeJS( 7470):         broadcast: [Function],
I/ReactNativeJS( 7470):         notify: [Function],
I/ReactNativeJS( 7470):         descriptorsDiscover: [Function],
I/ReactNativeJS( 7470):         valueRead: [Function],
I/ReactNativeJS( 7470):         valueWrite: [Function],
I/ReactNativeJS( 7470):         handleRead: [Function],
I/ReactNativeJS( 7470):         handleWrite: [Function],
I/ReactNativeJS( 7470):         handleNotify: [Function] } },
I/ReactNativeJS( 7470):   _peripherals: {},
I/ReactNativeJS( 7470):   _services: {},
I/ReactNativeJS( 7470):   _characteristics: {},
I/ReactNativeJS( 7470):   _descriptors: {},
I/ReactNativeJS( 7470):   _discoveredPeripheralUUids: [],
I/ReactNativeJS( 7470):   _events: { warning: [Function] } }

The piece of code i'm trying to test this on is a slightly modified version of one of nobles example codes:

> if (peripheral.advertisement.serviceUuids.includes("0000180900001000800000805f9b34fb")) {
      peripheral.connect(function(error) {
          peripheral.discoverServices(['0000180900001000800000805f9b34fb'], function(error, services) {
            var serviceIndex = 0;
            while (serviceIndex < services.length) {
              var batteryService = services[serviceIndex];
              batteryService.discoverCharacteristics(['00002a1c00001000800000805f9b34fb'], function(error, characteristics) {
                var characteristicIndex = 0;
                while (characteristicIndex < characteristics.length) {
                  var batteryLevelCharacteristic = characteristics[characteristicIndex];
                  batteryLevelCharacteristic.read(function(error, data) {
                    if (data) {
                      var string = data.toString('ascii');
                      var characteristicOut = data.toString('hex');
                    }
                  });
                  batteryLevelCharacteristic.on('data', function(data, isNotification) {
                    console.log(data);
                  });
                  batteryLevelCharacteristic.notify(true, function(error) {
                    console.log('battery level notification on');
                  });
                  characteristicIndex++;
                }
              });
              serviceIndex++;
            }
          });
        });
      }

Am I missing something or is the notify function purposely not included?

**Comment by Cody-G-G** [comment]
I am having the same issue.... Checking the code it does look like it's actually not included: 

https://github.com/jacobrosenthal/react-native-ble/blob/master/bindings.android.js

Weird omission, I'm hoping for a response but probably will try hacking around in the meantime cause I really depend on it...

**Comment by Cody-G-G** [comment]
btw there's actually a pull request for it, just hasn't been accepted yet:

https://github.com/jacobrosenthal/react-native-ble/pull/20

**Comment by jacobrosenthal** [comment]
Merged
