### ISSUE TITLE
this.RNBLE.getState is undefined

### ISSUE THREAD

**Issue by warrenronsiek** [jacobrosenthal/react-native-ble#24]
Hi, I'm making an extremely simple react-native scene using react-native-ble: 

```
import React from 'react';
const noble = require('react-native-ble');
import {Text, View} from 'react-native';

export default class NodeConfigScene extends React.Component {
  constructor(props) {
    super(props)
  }

  componentWillMount() {
    noble.on('stateChange', this._onStateChange);
    noble.on('discover', this._onDiscover);
  }

  _onStateChange (state) {
    if (state === 'poweredOn') {
      noble.startScanning();
    } else {
      noble.stopScanning();
    }
  };

  _onDiscover (item) {
    console.log(item);
  };
  
  render() {
    return(
      <View><Text>Scanning...</Text></View>
    )
  }
}
```

This code is extremely similar to the advertisement discovery example. However, when I launch my app, I get the following error redscreen: `undefined is not an object (evaluating 'this.RNBLE.getState')`

Since the example app that does almost exactly the same thing works, I'm suspecting this has something to do with my using [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) or [redux](https://github.com/reactjs/redux) (or something else) in the same app. 

Any ideas why I'm getting this error?

**Comment by warrenronsiek** [comment]
Nevermind. Forgot to link library. :facepalm:

**Comment by warrenronsiek** [comment]
For anyone else who runs into this, you first need to link the library as described under the install section of the Docs. Second, you need to edit your plist to allow the app to scan things. You do this by following the described answer in [this stackoverflow](http://stackoverflow.com/questions/22988363/how-to-resolve-the-nsinternalinconsistencyexception-error-in-objective-c).

**Comment by rclai** [comment]
Lol, close this.

**Comment by jacobrosenthal** [comment]
@warrenronsiek Thanks for solving yourself and following up with the answer :)
