### ISSUE TITLE
Tracking Android support

### ISSUE THREAD

**Issue by TrySpace** [jacobrosenthal/react-native-ble#3]
I see this doesn't support Android yet, Are there any plans to make it cross-platform?

Perhaps existing code from: https://github.com/don/BluetoothSerial can be used (cordova plugin) Or the less crossplatformy: https://github.com/randdusing/BluetoothLE

**Comment by jacobrosenthal** [comment]
not from me

**Comment by NishanthShankar** [comment]
You can have a look at https://github.com/axemclion/react-native-cordova-plugin to integrate cordova pugins with react-native android

**Comment by niftylettuce** [comment]
+1

**Comment by niftylettuce** [comment]
@NishanthShankar Do you know how to get it to work with RN 0.18+?  See https://github.com/axemclion/react-native-cordova-plugin/issues/14 when I try to use it in combination with https://github.com/randdusing/cordova-plugin-bluetoothle

**Comment by Shakarang** [comment]
@TrySpace I'm building the Android support on my fork of the repo. I've continued iOS development to read characteristics valued and it will be the same for Android

**Comment by rclai** [comment]
@Shakarang, would you like to collaborate together to get our changes to this repo? I noticed you've done a lot on the Android side. I've dealt mostly on the iOS side and was able to remove a lot of the noble code and just directly depend on the `noble` library.

**Comment by Shakarang** [comment]
@rclai I'll be really pleased to collaborate with you. Where did you code it? I can't find it in any branch..

**Comment by rclai** [comment]
It's here https://github.com/Profab/react-native-ble/tree/updates

**Comment by jacobrosenthal** [comment]
@Shakarang let us know if you get something that can be PR'ed

**Comment by Shakarang** [comment]
@jacobrosenthal Yep but currently I have no time with my work and school..

**Comment by rclai** [comment]
@Shakarang would you mind if I pick up from where you left off with the Android implementation?

**Comment by Shakarang** [comment]
@rclai Hey ! You can do it if you want. I will work on it on Saturday morning too.

**Comment by Shakarang** [comment]
@rclai Can you contact me on my email address please? It will be easier to exchange together.
It's maxime.junger@epitech.eu

**Comment by rclai** [comment]
Sure. I've been pretty busy lately so I don't know how much time I'll have to work on this, I'll let you know.

**Comment by jacobrosenthal** [comment]
Can you guys check out @Shakarang's PR? 
https://github.com/jacobrosenthal/react-native-ble/pull/11

**Comment by eriihine** [comment]
There's also following fork of react-native-ble for Android: 
 - https://github.com/eriihine/react-native-ble/tree/android

Most of the functionality is there (although not all) and it is still work in progress. 

This one uses the newer Android BLE API (API level 21 and up only). It also uses ScanRecord to parse scan result in more detail.

Just thought to mention this as well, in case some one is looking for API level 21 based solution. Would have pitched in here earlier, but noticed this thread just now.

**Comment by eriihine** [comment]
I probably will be working on the above android fork still on June and in August (bug fixes and remaining missing features). The target is to have it more or less ready at the end of august. 

Would be happy to contribute this as well if needed.

**Comment by jacobrosenthal** [comment]
@eriihine Thanks for posting, Ill check yours out as well when I get a chance.

**Comment by jacobrosenthal** [comment]
Any android people want to check these out. We have 2 competing options apparently
* @eriihine https://github.com/eriihine/react-native-ble/tree/android
* @Shakarang https://github.com/jacobrosenthal/react-native-ble/pull/11

Can we turn them into separate bindings and load the appropriate one based on a version check?

**Comment by ferologics** [comment]
@jacobrosenthal isn't https://github.com/eriihine/react-native-ble/tree/combined the latest version? I'm thinking of testing it

**Comment by jacobrosenthal** [comment]
@eriihine could clarify

**Comment by eriihine** [comment]
@ferologics You should checkout the android branch:
https://github.com/eriihine/react-native-ble/tree/android

The combined branch contains one minor tweak for iOS + android changes (ble.write event is sent out when writing to characteristic using withoutResponse attribute i.e. no response is needed from BLE but the event is send out in immediately after the write request has been processed). The iOS change is not needed necessarily.

The android branch contains only android specific changes.

**Comment by Shakarang** [comment]
@jacobrosenthal ?

**Comment by jacobrosenthal** [comment]
I presume your question is, have I looked at your fork yet? I havent and I havent got reports back from anyone else here either sadly. Have you looked at @eriihine's?

Ive got a nex5 here though in preparation but mainly Im working with @sandeepmistry to build tests around bindings layers so I can verify functionality (especially since Im not an android or java guy)

**Comment by Shakarang** [comment]
@jacobrosenthal Yes it was it, sorry. 

I've looked @eriihine's branch and it seems better than mine. I'm not specialised in Android so I may have some issues.

Do you think it will be available in the next weeks?

**Comment by jacobrosenthal** [comment]
Do I understand that you would prefer his merged over yours? Is there some features or anything about your branch that should be kept?

**Comment by franrios** [comment]
Is android support available yet?

**Comment by jacobrosenthal** [comment]
In the forks seen here. We need testers.

**Comment by jacobrosenthal** [comment]
I merged @eriihine's work for now as 1.0.7 and have a very simple example 'working' called advertisement_discovery. Im sure there are outstanding issues though, so please do try it.
