### ISSUE TITLE
Upgrade for compatibility with React-Native 0.40.0

### ISSUE THREAD

**Issue by warrenronsiek** [jacobrosenthal/react-native-ble#30]
Hi, when I use react-native-ble in the latest versions of react-native I get the following errors when building with Xcode:

<img width="338" alt="screen shot 2017-01-17 at 12 15 26 am" src="https://cloud.githubusercontent.com/assets/9755852/22013309/394561fe-dc4d-11e6-8846-2f401ee020ae.png">

Expected: 
Project compiles and runs without errors. 

Steps to reproduce:
1) Run:
```
react-native init test
cd test
npm install react-native-ble --save
rnpm link
```
2) Open project and run in Xcode.

Thank you!

**Comment by nazrdogan** [comment]
+1

**Comment by nazrdogan** [comment]
`react-native ugrade`   solve my problem.

**Comment by warrenronsiek** [comment]
`react-native upgrade` will remove the error. However, It will also overwrite the linking of the library. Unless I'm missing something, this is not a solution.

**Comment by rclai** [comment]
For now just go into the iOS project files and edit the React library imports to the right format of 0.40.0.

**Comment by connected-swu** [comment]
please merge https://github.com/jacobrosenthal/react-native-ble/pull/36
=P

**Comment by jacobrosenthal** [comment]
merged
