### ISSUE TITLE
noble.state is `unsupported` on evey other launch (iOS)

### ISSUE THREAD

**Issue by mattotodd** [jacobrosenthal/react-native-ble#33]
I find that on every other launch (if i use the react-native debug menu `Reload` or by killing the app and launching it again) on one load the state will be poweredOn and I'll get state updates if i turn on/off iOS bluetooth.

Then the next launch, state will be `unsupported` and I will get no state updates events.

It seems to flip flop, but every so often it will behave the same way on two subsequent launches.

Am I not shutting down noble properly?  Thoughts?

**Comment by warrenronsiek** [comment]
In my experience, there is some time between when you `require` react-native-ble and the time when it is turned on. If react native starts operating on it (e.g. setting listeners etc.), when it isn't turned on you end up getting this behavior.

I have solved this problem by simply putting in a redundant `require` statement earlier in my app's signup/login funnel. By the time the user has navigated to the point where I start using RNBLE, it is powered on and everything works. 

Disclaimer: I'm not an Android/IOS dev. I have no idea how or why this happens or even if what I'm saying makes sense. This is just what has worked for me in practice. You can test this by playing around with the scene you are using RNBLE in - create a button/timeout function that sets the event listeners and test the conditions that result in `unsupported`.

**Comment by jacobrosenthal** [comment]
merged
