### ISSUE TITLE
ios simulator app crashing with react-native-ble library installed

### ISSUE THREAD

**Issue by mosesmc52** [jacobrosenthal/react-native-ble#35]
I created a RN .4 project with installing the react-native-ble library installed. I made all the updates to the included library. The entire app builds successfully.  However, everytime I launch the IOS simulator with the react-native-blu library linked to the simulator it crashes. I see no error messages. Any insight the reason this maybe be occurring. 

Moses

**Comment by warrenronsiek** [comment]
RNBLE isn't supposed to work with your simulator. It needs to have access to a real phone, your simulator cant access the bluetooth capacities of your computer.

**Comment by mosesmc52** [comment]
got it.
