### ISSUE TITLE
Unable to resolve module 'url' 

### ISSUE THREAD

**Issue by mosesmc52** [jacobrosenthal/react-native-ble#38]
I'm loading noble on the app. 

var noble = require('noble');

I get this error, see attached screen shot. What do you suggest I do to fix it. 

![screen shot 2017-03-03 at 9 19 30 am](https://cloud.githubusercontent.com/assets/5233925/23556539/91680bd4-fff2-11e6-8520-d8b701875eb3.png)

**Comment by warrenronsiek** [comment]
How do you know this is a problem with RNBLE and not your app configuration? I checked the RNBLE dependencies, and the `url` module is not one of them. My guess is that unless you know that it is a problem with RNBLE, you are better off asking on StackOverflow.

**Comment by mosesmc52** [comment]
Ok

It could be an issue with the app configuration. I created a test app specifically to install and test **react-native-ble**. Here is my package.js file to display all the dependencies. On the main startup index page of the app I didn't change anything except include the noble library. 

{
  "name": "rnble_test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.42.0",
    "react-native-ble": "^1.0.7"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by warrenronsiek** [comment]
Ah, RNBLE isn't compatible with React Native 0.42.0. Until [this pull](https://github.com/jacobrosenthal/react-native-ble/pull/36) is merged, you need to downgrade to 0.39.0.

**Comment by jacobrosenthal** [comment]
Can anyone confirm that PR is good to go?

**Comment by jacobrosenthal** [comment]
merged

**Comment by mosesmc52** [comment]
I continued to experience this issue. I found the solution to be inserting this line into my package.js file.

    "browser": {
    "noble": "react-native-ble"
  }
