### ISSUE TITLE
Tracking connect, services, characteristics, reads and writes

### ISSUE THREAD

**Issue by export-mike** [jacobrosenthal/react-native-ble#4]
Hi,

I'm currently considering a react native ble plugin, may even port the existing ble central plugin from cordova (we're moving from cordova -> react-native), as that's what we're currently using. Then I've found this library, it would be cool if we could port the cordova implementation and apply it to the same noble-style interface and have it working with react-native.

So I'm just interested why you stopped at scanning?

**Comment by jacobrosenthal** [comment]
Yep, noble abstraction is way to go, as for cordova, theres really nothing to port from thin abstractions like this sadly. 

No good reason, I just havent needed any more than this for my work yet. PRs welcome

**Comment by rclai** [comment]
As some of you might know, I have been doing a lot of work to add the extra functionality on my fork, `updates` branch. I am not ready to submit a PR, but I am actively working on it since I am currently using it on this big project that involves using BLE. I expect to have the rest of the functionality completely done and conforming to the noble API more or less in the coming weeks.

**Comment by export-mike** [comment]
This is exciting! sadly the projectim on still hasn't moved to react native.

**Comment by jacobrosenthal** [comment]
@rclai Good job man. I still havent gotten around to getting back to this project or looking at your code. A big goal of mine is keeping the noble files as untouched as possible and pushing any needed changes upstream to @sandeepmistry eventually deduping them in our repo or merging into his domain. Whatever works.

**Comment by joelwass** [comment]
@rclai I don't see an updates branch in your fork, could you link us?

**Comment by rclai** [comment]
You're looking at the wrong fork. It's [here](https://github.com/Profab/react-native-ble/tree/updates).

**Comment by rclai** [comment]
I managed to get rid of all the copies of Noble files and directly depend on the `noble` NPM package itself. You can check it out [here](https://github.com/Profab/react-native-ble/tree/no-noble-copies). Right now if you test it you'll get a `binding` variable not found error, but that has been [fixed](https://github.com/sandeepmistry/noble/commit/38c55008c215d913cf8f5324e673951da96ffc79), we just need to wait for NPM package to get bumped up to reflect the fix.

**Comment by sandeepmistry** [comment]
@rclai noble v1.5.0 has been published with your fix :)

**Comment by rclai** [comment]
Thanks.

**Comment by jacobrosenthal** [comment]
@rclai just made a huge pr with what looks like all this. I published as 1.0.0 beta1 while I look at it myself.
Check it out everyone and give any feedback here
npm install react-native-ble@1.0.0-beta1

**Comment by jacobrosenthal** [comment]
Looks like you just npm install react-native-ble@1.0.0 actually

**Comment by jacobrosenthal** [comment]
@rclai Im still losing the initial getState in order to use the typical noble pattern of only scanning once we get a poweredOn state. Are you catching it with current code? Care to share a gist of your index.ios.js?

**Comment by rclai** [comment]
I know that the BlueTooth state gets lost sometimes, but in my experience it's not all the time. In an effort to make it more reliable, I moved the `setup` code into the `init` function, which I believe is a more appropriate and reliable place to put and we should be guaranteed to have an initial BlueTooth state. Try it now.

**Comment by rclai** [comment]
Here's my test gist: https://gist.github.com/rclai/104ffcd953ecfe6bad18b21fc0536f1b

**Comment by rclai** [comment]
Why does NPM still show the library as 0.0.7? https://www.npmjs.com/package/react-native-ble

**Comment by rclai** [comment]
FYI, I just rebased my PR and organized my commits in a more comprehensive way. Thankfully using `git rebase -i` was a very nice, intuitive learning process that wasn't painful.

**Comment by jacobrosenthal** [comment]
Its a beta release, you have to ask for it by name to get it. I THOUGHT you had to ask with the beta version but apparently not?

**Comment by rclai** [comment]
Oh okay. So were you able to test my new change with the Bluetooth state?

**Comment by jacobrosenthal** [comment]
Ive was fighting NPM. Your new code is released as
npm i react-native-ble@1.0.3-beta1

Im not sure what changed as it was overwritten, but note in you're not using the typical noble pattern of waiting for a state event, you're forcing it by checking the noble.state and scanning based on that --  because were still losing the state
https://gist.github.com/rclai/104ffcd953ecfe6bad18b21fc0536f1b#file-react-native-ble-test-index-ios-js-L36

**Comment by rclai** [comment]
There's no way of guaranteeing that the Bluetooth state is `poweredOn` even though my iPhone says that Bluetooth is on, that's why I'm doing that. I check the state on the `init` function in order to always have the state, especially during Live Reload mode.

**Comment by jacobrosenthal** [comment]
Agreed. Thats why the noble pattern is to just wait until you get that
first onstatechange event
Heres my patched branch, this hack is what will have to do.
https://github.com/jacobrosenthal/react-native-ble/blob/1.0.3/bindings.ios.js#L137

I also pulled out the peripheral stuff. We should start a
react-native-bleno for that in order to stay true to node

**Comment by rclai** [comment]
Oh yeah, I was about to take out the peripheral stuff after noticing that since I'm depending on `noble`, that stuff was going to break.

**Comment by rclai** [comment]
Okay I updated my PR and the peripheral stuff is no longer there.

**Comment by rclai** [comment]
Is it necessary to put a `setTimeout` to `getState`? I think the issue of the state being `unknown` may still arise.

**Comment by jacobrosenthal** [comment]
Were trying to be like noble, and I dont believe noble guarantees has a known state on startup. It asks you to wait for an onchange event. Our problem has been were always missing that event, hence my final terrible hack.

You dont have to update, Ill used my patched fork, itll maintain all your authorship.

**Comment by rclai** [comment]
Cool, I see you update your example. Did it all work?

**Comment by jacobrosenthal** [comment]
Yep. Havent used it super thoroughly but looks good. Nobody else tested
anything yet?

**Comment by jacobrosenthal** [comment]
Well with no other feedback the few tests Ive run work well. Good job and thanks @rclai . Published it as 1.0.3 (.3 because of my previous fighting with npm--dont ask)

**Comment by arahansen** [comment]
Hey everyone, the discussion on introducing peripheral support is of interest to me. Has there been any work done to this repo (or maybe another repo) to add peripheral support for React Native?

**Comment by rikardwissing** [comment]
I'm also interested in peripheral support for react native
