### ISSUE TITLE
Different UUID format when running in my RN app and directly from noble/example/advertisement.js

### ISSUE THREAD

**Issue by bitabs** [jacobrosenthal/react-native-ble#58]
In my App, I'm trying to connect to an arduino using react-native-ble.

I've followed this [`step`](https://github.com/sandeepmistry/noble#windows)

When I run it in noble/example/advertisement.js, it returns the following:
<img width="928" alt="capture" src="https://user-images.githubusercontent.com/16179773/35704107-3878494c-0796-11e8-8b25-3d6b1d266b92.PNG">

But when I try to search it in my App, I get the following:

<img width="1063" alt="capture" src="https://user-images.githubusercontent.com/16179773/35704089-2e5553ec-0796-11e8-8164-d336a48a3caf.PNG">

This is a big issue because I cant connect to my arduino.

My services UUID should be 4 digits long for example:

Should be
=
```
1800
1801
2220
```
Not:
=
```
0000180000001....
0000180100001....
0000222100001....
```

Why is this happening?

Update
=
I've tested and its confirmed that it's only this library that prints the following:
<img width="724" alt="capture" src="https://user-images.githubusercontent.com/16179773/35706600-47f5d8d2-079e-11e8-8a77-8595f65b0865.PNG">

What change is required in order to provide the correct UUID?

**Comment by bitabs** [comment]
@jacobrosenthal I've also posted this on [`StackOverflow`](https://stackoverflow.com/questions/48581823/why-is-my-ble-service-uuid-different-in-android-and-iphone) for clarity

**Comment by Chzzs** [comment]
Hi @NaseebullahSafi 
Those are the full 128-bit-uuid not the shorthand version.
You can find more info [there](https://stackoverflow.com/questions/36212020/how-can-i-convert-a-bluetooth-16-bit-service-uuid-into-a-128-bit-uuid) if you are looking for a workaround.

Please let me know if you found any solution in this.

**Comment by bitabs** [comment]
@Chzzs Really appreciate it, that's really handy. Can it be done in client side? In other words, as soon as I receive it I apply the calculation in js for example?

**Comment by Chzzs** [comment]
>  Can it be done in client side? In other words, as soon as I receive it I apply the calculation in js for example? 

I guess so...   This is basically the same service, why don't you listen for both UUID instead ?

**Comment by bitabs** [comment]
@Chzzs Yup managed to do that. Thank you!
